### ISSUE TITLE
How to change scroll direction?

### ISSUE THREAD

**Issue by xhzengAIB** [weitzel926/StatusFlow#1]
@weitzel926 
Hi!  
If i need the vertical scroll? How should i do it?

Jack

**Comment by weitzel926** [comment]
Hi Jack,

I'm planning on adding it in the next release.  Right now, it isn't supported.  That said, I have already have prototype code.  I just need to write some tests for it and refactor a little.  I should be able to get to it within the week.  Technically, it just needs a flag to set the direction and the correct calculations in the custom flow layout.  

thanks,

Wade

**Comment by weitzel926** [comment]
@xhzengAIB 
Hi Jack,

The initial implementation of vertical mode is in 0.0.3.  Documentation in the README.  

thanks,

Wade

**Comment by xhzengAIB** [comment]
@weitzel926 
Thank you very much. I will check it out.
