### ISSUE TITLE
Required Top and Bottom box with custom size, possible?

### ISSUE THREAD

**Issue by nikunjsilicon** [weitzel926/StatusFlow#2]
Hi weitzel926,

Your demo is excellent and its work for me in both orientation but I want to integrate top and bottom box with custom width and height like 60x60 but center box is 80x80 so can you please suggest me how can I do this? and PFA of landscape mode with Top, Center and Bottom box of my issue.

Thanks in advance for help.
Nikunj Jadav

![simulator screen shot 06-nov-2015 4 27 02 pm](https://cloud.githubusercontent.com/assets/11506312/10995549/a58a7f00-84a3-11e5-9d04-a0a393820143.png)

**Comment by weitzel926** [comment]
Sorry for the delayed response.  That math is currently in WDWStatusFlowLayout, modifyAttributes method.  It is just making the non-middle cells half the size as the middle one, without changing their aspect ratios.  This can be as complex as you want.  I kept it simple for now.
